### ISSUE TITLE
upgrade to vbb-hafas@5

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/vbb-get-off-bot#1]
[`vbb-hafas`](https://npmjs.com/package/vbb-hafas)`@5` is based on [`hafas-client`](https://npmjs.com/package/hafas-client)`@3`, which has a new output format. Minor adjustments must be made in the code.

**Comment by Ankcorn** [comment]
Hey I would like to work on this 👍

**Comment by derhuerst** [comment]
Sure, go ahead! Comment here or in your work-in-progress PR whenever you have questions.

**Comment by derhuerst** [comment]
FYI @ThomasAnkcorn has tackled this in #4.
